apiVersion: v1
kind: Pod
metadata:
  name: pod-secret22
spec:
  containers:
    - image: nginx
      name: myc1-new
      volumeMounts:
        - name: foo
          mountPath: "/etc/foo"
          readOnly: true

  volumes:
    - name: foo
      secret:
        secretName: secret7
